### ISSUE TITLE
appState: поддержать falsy параметры в url

### ISSUE THREAD

**Issue by lastw** [2gis/slot#164]
Сейчас, если значение параметра равно, к примеру, 0 или false, в url оно пойдет как пустая строка.

https://github.com/2gis/slot/blob/b6c5497828572a6d1e98eb61b772a256eb4d27f4/components/appState/uri/pattern.js#L156

1) Нужно в Pattern#inject не приводить такие значения к пустой строке
2) [возможно] Нужно сделать поддержку дефолтного валидатора (`'*'`)

**Comment by Diokuz** [comment]
https://github.com/2gis/slot/pull/187

**Comment by lastw** [comment]
0 и false теперь идут в url как есть https://github.com/2gis/slot/pull/187
